#!/usr/bin/env bash

#https://github.com/huggingface/transformers/tree/master/examples/pytorch/language-modeling

MODEL=gpt2

python train_clm.py \
    --model_name_or_path ${MODEL} \
    --train_file data/dataset_train.txt \
    --validation_file data/dataset_validation.txt \
    --do_train \
    --do_eval \
    --use_fast_tokenizer \
    --overwrite_output_dir \
    --output_dir .models/$(date '+%Y-%m-%d_%H-%M')_${MODEL} \
    --per_device_eval_batch_size 20 \
    --per_device_train_batch_size 5 \
    --num_train_epochs 10 \
    --block_size 256 \
    --save_steps 2000
