apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: RHT text generation runtime
  name: rht-text-generator-runtime
spec:
  containers:
    - image: quay.io/jramcast/rht-text-generator:model-serving-runtime-cpu-0.1.1
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch